import type { Template } from "./types";
import { uid } from "./utils";

export const TEMPLATES: Template[] = [
  {
    id: "fitness",
    name: "Personal Trainer",
    niche: "Fitness & Saúde",
    profile: {
      username: "fit_coach",
      displayName: "Coach Bruno Silva",
      bio: "💪 Transformação corporal\n🏋️ Personal Trainer certificado\n📊 Planos personalizados",
      link: "",
      bioLinks: [
        { id: uid(), label: "Agende sua aula experimental", url: "https://link.com/aula" },
        { id: uid(), label: "Planos e programas", url: "https://link.com/planos" },
      ],
      posts: "127",
      autoCount: false,
      followers: "15.2K",
      following: "842",
      avatarUrl: null,
      verified: "blue",
      category: "Personal Trainer",
      ctaLabel: "Agendar",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Treinos", coverUrl: null },
      { id: uid(), name: "Antes/Depois", coverUrl: null },
      { id: uid(), name: "Dicas", coverUrl: null },
      { id: uid(), name: "Receitas", coverUrl: null },
    ],
    feed: [],
  },
  {
    id: "food",
    name: "Restaurante Gourmet",
    niche: "Gastronomia",
    profile: {
      username: "sabor_gourmet",
      displayName: "Sabor Gourmet",
      bio: "🍽️ Culinária contemporânea\n👨‍🍳 Chef premiado\n📍 São Paulo - Jardins\n🕐 Ter-Dom 12h-23h",
      link: "",
      bioLinks: [
        { id: uid(), label: "Reserve sua mesa", url: "https://reservas.com" },
        { id: uid(), label: "Cardápio completo", url: "https://menu.com" },
        { id: uid(), label: "Delivery", url: "https://delivery.com" },
      ],
      posts: "543",
      autoCount: false,
      followers: "28.7K",
      following: "356",
      avatarUrl: null,
      verified: "gold",
      category: "Restaurante",
      ctaLabel: "Reservar",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Menu", coverUrl: null },
      { id: uid(), name: "Ambiente", coverUrl: null },
      { id: uid(), name: "Chef", coverUrl: null },
      { id: uid(), name: "Eventos", coverUrl: null },
    ],
    feed: [],
  },
  {
    id: "fashion",
    name: "Loja de Moda",
    niche: "Moda & Estilo",
    profile: {
      username: "style.boutique",
      displayName: "Style Boutique",
      bio: "✨ Moda feminina exclusiva\n🛍️ Peças autorais\n📦 Entrega em todo Brasil\n💳 Parcele em até 6x",
      link: "",
      bioLinks: [
        { id: uid(), label: "Compre online", url: "https://loja.com" },
        { id: uid(), label: "Coleção outono/inverno", url: "https://loja.com/colecao" },
        { id: uid(), label: "Outlet até 50% off", url: "https://loja.com/outlet" },
      ],
      posts: "892",
      autoCount: false,
      followers: "45.3K",
      following: "1.2K",
      avatarUrl: null,
      verified: "blue",
      category: "Loja de roupas",
      ctaLabel: "Comprar",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Novidades", coverUrl: null },
      { id: uid(), name: "Looks", coverUrl: null },
      { id: uid(), name: "Promoções", coverUrl: null },
      { id: uid(), name: "Depoimentos", coverUrl: null },
    ],
    feed: [],
  },
  {
    id: "beauty",
    name: "Clínica de Estética",
    niche: "Beleza & Bem-estar",
    profile: {
      username: "beleza.clinica",
      displayName: "Clínica Beleza & Cia",
      bio: "💆‍♀️ Tratamentos faciais e corporais\n💉 Harmonização facial\n🌟 Resultados comprovados\n📅 Agende sua avaliação",
      link: "",
      bioLinks: [
        { id: uid(), label: "Agendar avaliação gratuita", url: "https://agenda.com" },
        { id: uid(), label: "Nossos tratamentos", url: "https://tratamentos.com" },
      ],
      posts: "324",
      autoCount: false,
      followers: "12.8K",
      following: "543",
      avatarUrl: null,
      verified: "blue",
      category: "Clínica de estética",
      ctaLabel: "Agendar",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Procedimentos", coverUrl: null },
      { id: uid(), name: "Resultados", coverUrl: null },
      { id: uid(), name: "Dúvidas", coverUrl: null },
      { id: uid(), name: "Promoções", coverUrl: null },
    ],
    feed: [],
  },
  {
    id: "architect",
    name: "Arquitetura & Design",
    niche: "Arquitetura",
    profile: {
      username: "arq.designer",
      displayName: "Marina Oliveira",
      bio: "🏠 Arquitetura residencial\n✏️ Design de interiores\n🎨 Projetos personalizados\n📐 CAU 123456-7",
      link: "",
      bioLinks: [
        { id: uid(), label: "Portfólio completo", url: "https://portfolio.com" },
        { id: uid(), label: "Solicite um orçamento", url: "https://orcamento.com" },
      ],
      posts: "267",
      autoCount: false,
      followers: "22.4K",
      following: "987",
      avatarUrl: null,
      verified: "blue",
      category: "Arquiteta",
      ctaLabel: "Orçamento",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Projetos", coverUrl: null },
      { id: uid(), name: "Obras", coverUrl: null },
      { id: uid(), name: "Inspirações", coverUrl: null },
      { id: uid(), name: "Processo", coverUrl: null },
    ],
    feed: [],
  },
  {
    id: "marketing",
    name: "Agência Digital",
    niche: "Marketing Digital",
    profile: {
      username: "agencia.digital",
      displayName: "Digital Marketing Pro",
      bio: "🚀 Estratégias de crescimento\n📱 Social Media & Ads\n📊 Resultados mensuráveis\n💼 +200 clientes atendidos",
      link: "",
      bioLinks: [
        { id: uid(), label: "Análise gratuita do seu Instagram", url: "https://analise.com" },
        { id: uid(), label: "Cases de sucesso", url: "https://cases.com" },
        { id: uid(), label: "Fale conosco", url: "https://contato.com" },
      ],
      posts: "1.2K",
      autoCount: false,
      followers: "38.9K",
      following: "2.1K",
      avatarUrl: null,
      verified: "gold",
      category: "Agência de marketing digital",
      ctaLabel: "Consultar",
      storyActive: true,
      viewMode: "visitor",
    },
    highlights: [
      { id: uid(), name: "Cases", coverUrl: null },
      { id: uid(), name: "Dicas", coverUrl: null },
      { id: uid(), name: "Equipe", coverUrl: null },
      { id: uid(), name: "Tendências", coverUrl: null },
    ],
    feed: [],
  },
];
